### ISSUE TITLE
pysysp package cannot be used on python3

### ISSUE THREAD

**Issue by Firestar-Reimu** [mdusilva/pysysp#1]
from https://github.com/nleethochawalit/GLACiAR2-master

Note on pysysp package* The current version pip install pysysp is for python2. To make the code runs with python3, a few lines in the installed pysysp need to be changed.

In pysysp.py, change "import pyfits" to "import astropy.io.fits as pyfits"
In pysysp.py, change "import extinction as extlaws" to "from . import extinction as extlaws"
In init.py, chage "from pysysp import StarSpectrum, BandPass, showfilters, listlaws" to "from .pysysp import StarSpectrum, BandPass, showfilters, listlaws"

**Comment by mdusilva** [comment]
I'd uploaded a new version compatible with Python3.
